version: '3'

services:
  cartography:
    image: williamjackson/cartography
    build: .
  neo4j:
    image: neo4j:3.5.12
    environment:
      NEO4J_AUTH: none
    volumes:
      - neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687

volumes:
  neo4j-data:
